### PR TITLE
(WIP) IDE: AppController: resurrect terminal sessions from activeSessions 

### PR DESCRIPTION
**Pull request by gokmen**

### CODE REVIEW

**Comment by gokmen** [comment]
This one is ready actually, but since it's not keeping sessions based on workspaces, it will open the same sessions again even you are not in same workspace. I did it because it was missing, but leaving you guys if want to improve or close this at all. cc/ @fatihacet @szkl @sinan

**Comment by sinan** [comment]
@szkl @fatihacet can you guys find out how to bind this to workspaces?

**Comment by fatihacet** [comment]
We need to discuss about it.

**Comment by fatihacet** [comment]
Merged into `sidebar-refactor` branch and I will continue development on this branch. Closing this one. Thanks @gokmen.

**Pull request closed without merging**
