### PR TITLE
ide: resolved bug(Filetree was displayed twice)

### PR DESCRIPTION
**Pull request by andrushkevich**
@sinan @fatihacet @usirin plz review. 
now we don't mount machine if it's not active.

### CODE REVIEW

**Comment by fatihacet** [comment]
This would probably fix the double mounted file tree issue. But as far I remember, this is may not be the best fix. Instead of returning before mounting the second file tree, let's solve the root cause. Actually it's a bug from the beginning of the IDE and if I am not wrong, here is the case to reproduce it.

- Open your workspace on your VM1. VM1 should be started and working fine.
- Create another VM if you don't have and stop if it's running and start your VM2.
- Go back to VM1 and wait until VM2 is started.
- When VM2 is started, it will want to mount VM2's file tree to VM2's workspace but the buggy code on the IDE will mount it to VM1 workspace because it is currently active and it's the frontApp of the appManager. This will lead the double file tree issue.

With your changes we will never see double file tree but also in VM2's workspace there won't be any file tree mounted. I guess, we are telling the `appManager.frontApp` to mount the file tree and this is the reason of this bug.

I hope, I can tell the problem clearly. Can you please test the steps above and if it is a valid case can you fix

**Comment by fatihacet** [comment]
Any update on this?

**Comment by andrushkevich** [comment]
@fatihacet:  Could you check following video http://recordit.co/LzWtwGoIuu ? I've recorded steps that you described.

**Comment by fatihacet** [comment]
That looks fine. Thanks @andrushkevich.

**Pull request merged**
